services:
  product-service:
    image: pasanbaddewithana1234/product-service:latest
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      - MONGO_URI=mongodb+srv://it21247804:Lonewolf1234@afassignment.1ukrjs4.mongodb.net/CTSE?retryWrites=true&w=majority
    restart: unless-stopped
   

