services:
  product-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      # Use the environment variable from .env file
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5002/api/products"]
      interval: 30s
      timeout: 10s
      retries: 3