services:
  product-service:
    image: pasanbaddewithana1234/product-service:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - product-network
    restart: unless-stopped

networks:
  product-network:
    driver: bridge
    name: product-network