services:
  product-service:
    image: pasanbaddewithana1234/product-service:latest
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
   

